services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

# URL: http://localhost:8081
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379

volumes:
  redis:
    driver: local
